# Generated by Django 5.1.5 on 2025-02-03 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expire_date', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_date', models.DateField()),
                ('join_date', models.DateField()),
                ('phone_no', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='last_credit_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('speeding', 'Speeding'), ('ignition', 'Ignition'), ('parking', 'Parking'), ('idling', 'Idling'), ('offline', 'Offline')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='is_ignition_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_parked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='total_mileage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='active_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_driver', to='api.driver'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.JSONField()),
                ('end_location', models.JSONField(blank=True, null=True)),
                ('distance_km', models.FloatField(default=0.0)),
                ('average_speed_kmh', models.FloatField(default=0.0)),
                ('max_speed_kmh', models.FloatField(default=0.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.device')),
            ],
        ),
    ]
