# Generated by Django 5.1.5 on 2025-02-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('report_to', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('General', 'General'), ('Bug', 'Bug'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], default='General', max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
