# Generated by Django 5.1.5 on 2025-02-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_feedback_report_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_imei',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_card_iccid',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_card_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_imsi',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
