# Generated by Django 5.1.5 on 2025-02-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_device_device_imei_device_device_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
